version: '3.8'

volumes:
  postgres-data:

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    netowrk_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stoped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
