on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: false
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: false
        build_id:
          required: false
          type: string
        deploy_target:
          required: false
          type: string
        perform_deploy:
          required: false
          type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
      - run: echo "Log level"

        
