on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: true
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: false
        build_id:
          required: true
          type: string
        deploy_target:
          required: true
          type: string
        perform_deploy:
          required: true
          type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "build_id: $build_id"
          echo "deploy_target: $deploy_target"
          echo "perform_deploy: $perform_deploy"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
        
